#!/usr/bin/ash

run_hook() {
    # Configure TPM
    chown tss:tss /dev/tpm0
    chmod 600 /dev/tpm0
    sleep 1

    # Start tcsd
    if [ -f /usr/bin/tcsd ]; then
        /sbin/tcsd
    fi

    # Get key from TPM NVRAM
    echo TPM... getting secret from NVRAM
    /etc/tpm-secret/tpm_getsecret.sh > /secret_key.bin
    chmod 0400 /secret_key.bin
}

# Run as `/etc/hooks/tpm run_hook` to run the function()
"$@"
